### ISSUE TITLE
error TS2304: Cannot find name 'HelloYouComponent

### ISSUE THREAD

**Issue by cybersultan** [ButterCMS/buttercms-angular-tutorial#1]
This component is missing when installed.What this component is for gentlemen?

**Comment by jakelumetta** [comment]
@cybersultan Ah we forgot to commit a folder to the repo. Thanks for the heads up, we'll fit it shortly.

**Comment by jakelumetta** [comment]
@cybersultan Fixed with https://github.com/ButterCMS/buttercms-angular-tutorial/commit/d79ffaecaffde42051f4120e2089e8a77dd325ed

Can you try again?

**Comment by Methodician** [comment]
I recommend closing this. It's not relevant to new users or contributors.

**Comment by jakelumetta** [comment]
Agreed. Lost track of this one. Thanks!
