### ISSUE TITLE
[ts] Cannot find module '@angular/core/testing'.

### ISSUE THREAD

**Issue by conorH22** [ButterCMS/buttercms-angular-tutorial#3]
Error occurred in src/ app/hello-you/hello-you-component.ts in the import section for the buttercms-angular-tutorial  in Visual Studio Code version 1.21. to fix change the  '' to "".
`import {Component, OnInit} from '@angular/core';`     
to
`import {Component, OnInit} from "@angular/core";`

**Comment by jakelumetta** [comment]
Thanks @conorH22  - we'll take a look

**Comment by conorH22** [comment]
I have updated VS code to 1.22. The problem does not occur anymore.

**Comment by jakelumetta** [comment]
@conorH22 Great thanks for letting us know
